# Generated by Django 4.0.1 on 2022-01-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hy', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
